name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout code
    
   ## - uses: actions/checkout@v4
   ## - name: Build the Docker image
   ##   run: docker build . --file Dockerfile --tag video-streaming:latest
    - uses: docker/login-action@v2
    - name: login to hub  
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v4
    - name: Build and push
      with:
        context: .
        push: true
        tags: video-streaming:latest
